spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/patent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root