spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sihgyu
    url: jdbc:mysql://47.100.162.184:3306/patent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.greenism.patent.entity
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl